### DISCUSSION TITLE
Run in github actions for preview

### DISCUSSION THREAD

**Discussion by levino** [harlan-zw/unlighthouse#172] [Q&A]
Hello everyone, I would like to run `unlighthouse-ci` for my nextjs app before I merge the code to main and deploy to production. I think I should either start a nextjs production server with the current code changes before running `unlighthouse-ci` in ci or point it to the vercel preview app. However I cannot find a way to configure a `start script` for `unlighthouse-ci` to run a local nextjs server and I also struggle to trigger the `lighthouse-ci` run based on the successful vercel preview deployment AND scope the following check to the PR and have it available as a check that would prevent merging the PR when unsuccessful. Does anyone have an example how it can work? [My code lives here](https://github.com/levino/roessing.de).

**Comment by Charlie284** [comment]
You do not need a `start` option inside Unlighthouse. Start and stop the application outside it, then point `unlighthouse-ci` at the ready URL.

In fact, the local-preview solution was added to your repository later the same day as this question ([package scripts](https://github.com/dorfentwicklungskreis-roessing/roessing.de/blob/e5ada47af6afb310ec35d823d83b17ae43c968cd/package.json) and [workflow](https://github.com/dorfentwicklungskreis-roessing/roessing.de/blob/e5ada47af6afb310ec35d823d83b17ae43c968cd/.github/workflows/checks.yml)). The relevant scripts were:

```json
{
  "start": "next start",
  "unlighthouse": "unlighthouse-ci --site http://localhost:3000",
  "performance:check": "start-server-and-test 'bun start' 3000 'bun run unlighthouse'"
}
```

and the pull-request workflow built the app and ran `bun performance:check`. `start-server-and-test` starts Next, waits for port 3000, runs Unlighthouse, and tears the server down. Because `unlighthouse-ci` exits nonzero when the configured budget fails, that `performance` job is already a normal PR check. Select the check GitHub shows for that `performance` job as required in the branch ruleset to block merging on failure. This is the simpler and more reproducible option because the audit and build use the exact PR checkout without waiting for an external deployment.

If you specifically need the Vercel preview environment, Vercel now recommends its `repository_dispatch` events instead of `deployment_status`. A minimal current workflow is:

```yaml
name: Unlighthouse preview

on:
  repository_dispatch:
    types: ['vercel.deployment.ready']

jobs:
  audit:
    if: github.event.client_payload.environment == 'preview'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      statuses: write

    steps:
      - name: Publish status on the deployed commit
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: Unlighthouse preview
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the deployed commit
        uses: vercel/repository-dispatch/actions/checkout@v1

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install --global @unlighthouse/cli puppeteer

      - name: Audit Vercel preview
        run: unlighthouse-ci --site "$PREVIEW_URL"
        env:
          PREVIEW_URL: ${{ github.event.client_payload.url }}
```

Enable repository-dispatch events in the Vercel project's Git settings and commit this workflow to the default branch. The two Vercel actions matter: a `repository_dispatch` workflow normally runs in the context of the default branch, while these actions check out `client_payload.git.sha` and publish the final pass/fail status on that deployed SHA. You can then require the exact `Unlighthouse preview` status in the branch ruleset.

If the preview has Vercel Deployment Protection enabled, the runner also needs an authorized way to reach it; otherwise Lighthouse will audit the protection page rather than the application.

References: [Vercel repository-dispatch events and payload](https://github.com/vercel/repository-dispatch) and [Vercel's GitHub integration guide](https://vercel.com/docs/git/vercel-for-github#repository-dispatch).
